---
title: "Tables_Wild_2024"
author: Kristoffer Wild
date: "`r Sys.Date()`"
output: 
  word_document:
    reference_docx: template.docx
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, eval = T, echo = FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE)
options(digits = 2)
rm(list=ls())
sessionInfo()
pacman::p_load(car, dplyr,ggplot2, flextable, lubridate, knitr, here, stringr, broom, tibble, tidyverse)
```

## Tables

**Table S1**. Basal, OXPHOS, LEAK, RCR  ANOVA model output. 
```{r}
#| echo: false

Basal_treatment_mod <- readRDS('Kwild_code/models/Basal_treatment_mod.RDS')
ADP_treatment_mod <- readRDS('Kwild_code/models/ADP_treatment_mod.RDS')
Oligo_treatment_mod<- readRDS('Kwild_code/models/Oligo_treatment_mod.RDS')
RCR_mod <- readRDS('Kwild_code/models/RCR_mod.RDS')

# combinde data
ANOVA_Basal_treatment_mod <- tidy(Anova(Basal_treatment_mod)) %>% 
  mutate(significant = ifelse(p.value < 0.05, TRUE, FALSE)) %>%
  mutate(across(where(is.numeric), round, 3)) %>% 
  mutate(Test = 'Basal')
ANOVA_ADP_treatment_mod <- tidy(Anova(ADP_treatment_mod))%>% 
  mutate(significant = ifelse(p.value < 0.05, TRUE, FALSE)) %>%
  mutate(across(where(is.numeric), round, 3))  %>% 
  mutate(Test = 'OXPHOS')
ANOVA_Oligo_treatment_mod <- tidy(Anova(Oligo_treatment_mod))%>% 
  mutate(significant = ifelse(p.value < 0.05, TRUE, FALSE)) %>%
  mutate(across(where(is.numeric), round, 3)) %>% 
  mutate(Test = 'LEAK')
ANOVA_RCR_mod <- tidy(Anova(RCR_mod))%>% 
  mutate(significant = ifelse(p.value < 0.05, TRUE, FALSE)) %>%
  mutate(across(where(is.numeric), round, 3)) %>% 
  mutate(Test = 'RCR')
S1_mods <- rbind(ANOVA_Basal_treatment_mod,
                 ANOVA_ADP_treatment_mod,
                 ANOVA_Oligo_treatment_mod,
                 ANOVA_RCR_mod)
S1_mods <- S1_mods[,c(7, 1, 2, 3, 4, 5, 6)]
TblS1<-flextable(S1_mods) %>%
  flextable::font(part = "all", fontname = "Times New Roman") %>%
  hline(i=c(8,16, 24, 32), j = 1:7, part="body") %>% 
  set_table_properties(layout = "autofit") %>%
  fix_border_issues(part = "body") %>%
  bold(i = ~ significant == TRUE, bold = TRUE, part = "body") %>% 
  delete_columns(j = 'significant') %>% 
  merge_v(j = "Test")

knitr::knit_print(TblS1)
```

\newpage
**Table S2**. Mass ANOVA model output. 
```{r}
#| echo: false
Mass_basal <- Anova(readRDS('Kwild_code/models/Mass_basal.RDS'))%>% 
  tidy() %>% 
  mutate(Test = 'Basal')
Mass_Growth_ADP <- Anova(readRDS('Kwild_code/models/Mass_Growth_ADP.RDS'))%>%
  tidy() %>% 
  mutate(Test = 'OXPHOS')
Mass_Growth_Oligo <- Anova(readRDS('Kwild_code/models/Mass_Growth_Oligo.RDS'))%>%
  tidy() %>% 
  mutate(Test = 'Leak')
Mass_Growth_RCR <- Anova(readRDS('Kwild_code/models/Mass_Growth_RCR.RDS'))%>%
  tidy() %>% 
  mutate(Test = 'RCR')


#### Table
Mass_table <- rbind(Mass_basal, Mass_Growth_ADP, Mass_Growth_Oligo, Mass_Growth_RCR)%>% 
  mutate(significant = ifelse(p.value < 0.05, TRUE, FALSE)) %>%
  mutate(across(where(is.numeric), round, 3))

# combine and rearrange
Table_S2 <- Mass_table[,c(6, 1, 2, 3, 4, 5, 7)]

TblS2<-flextable(Table_S2) %>%
  flextable::font(part = "all", fontname = "Times New Roman") %>%
  hline(i=c(5, 10, 15, 20), j = 1:7, part="body") %>% 
  bold(i = ~ significant == TRUE, bold = TRUE, part = "body") %>% 
  delete_columns(j = 'significant') %>%
  merge_v(j = "Test") %>% 
  set_table_properties(layout = "autofit") %>%
  fix_border_issues(part = "body")

knitr::knit_print(TblS2)
```
\newpage

**Table S3** SVL ANOVA model output. 
```{r}
#| echo: false
SVL_basal <- Anova(readRDS('Kwild_code/models/Mass_basal.RDS')) %>% 
  tidy() %>% 
  mutate(Test = 'BASAL')
SVL_Growth_ADP <- Anova(readRDS('Kwild_code/models/SVL_Growth_ADP.RDS')) %>% 
  tidy() %>% 
  mutate(Test = 'OXPHOS')
SVL_Growth_Oligo <- Anova(readRDS('Kwild_code/models/SVL_Growth_Oligo.RDS')) %>% 
  tidy() %>% 
  mutate(Test = 'Leak')
SVL_Growth_RCR <- Anova(readRDS('Kwild_code/models/SVL_Growth_RCR.RDS')) %>% 
  tidy() %>% 
  mutate(Test = 'RCR')


# combine and rearrange
SVL_Growth_ADP_table <- rbind(SVL_basal, SVL_Growth_ADP, SVL_Growth_Oligo, SVL_Growth_RCR)%>% 
  mutate(significant = ifelse(p.value < 0.05, TRUE, FALSE)) %>%
  mutate(across(where(is.numeric), round, 3)) 
Table_S3 <- SVL_Growth_ADP_table[,c(6, 1, 2, 3, 4, 5, 7)]


TblS3<-flextable(Table_S3) %>%
  flextable::font(part = "all", fontname = "Times New Roman") %>%
  hline(i=c(5, 10, 15, 20), j = 1:7, part="body") %>% 
  bold(i = ~ significant == TRUE, bold = TRUE, part = "body") %>% 
  delete_columns(j = 'significant') %>%
  merge_v(j = "Test") %>% 
  set_table_properties(layout = "autofit") %>%
  fix_border_issues(part = "body")

knitr::knit_print(TblS3)
```
